name: build

on: [push]

jobs:
  build:
    name: continuous-integration
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: build
        run: go build main.go
