name: build

on:
  push:
    branches:
      - main
    paths:
      - '**/*.rs'
  pull_request:
    paths:
      - '**/*.rs'

jobs:
  build:
    name: continuous-integration
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Lint
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Test
        run: cargo test

      - name: Build release binary
        run: cargo build --release
