name: build

on: [push]

jobs:
  build:
    name: continuous-integration
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5.4.0
        with:
          go-version: 1.24.0

      - name: Build
        run: go build main.go

      - name: Show help
        run: ./main --help
